name: Build CI

on:
  push:
    branches:
      - 'xxf098/develop'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup scala
      run: |
        # sudo apt-get remove scala-library scala
        sudo wget www.scala-lang.org/files/archive/scala-2.11.8.deb
        sudo dpkg -i scala-2.11.8.deb
    - name: Setup SBT
      run: |
         echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
         sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
         sudo apt-get update
         sudo apt-get install sbt
    - name: Setup Package
      run: |
        sudo apt-get --quiet install --yes wget tar unzip gcc-multilib g++-multilib libstdc++6 libgcc1 zlib1g libncurses5  
    - name: Build apk
      run: |
        ./travis-ci/setup.sh
    - name: Check Build
      run: |
        pwd
        ls -lh ./target/android/output/
        echo test, and deploy your project.
